### ISSUE TITLE
Offsets

### ISSUE THREAD

**Issue by hayk4500** [IMXNOOBX/cs2-external-esp#1]
```
#define dwLocalPlayer 0x17142C8
#define dwEntityList 0x167ABA8
#define dwPawnHealth 0x808
#define dwPlayerPawn 0x5dc
#define dwViewMatrix 0x1714C70
#define dwSanitizedName 0x720
#define m_iTeamNum 0x3bf
#define m_vecOrigin 0x12AC
```

**Comment by IMXNOOBX** [comment]
Updated in commit: https://github.com/IMXNOOBX/cs2-external-esp/commit/269d3fb76837884d879811985a67d5183d296602

Exact lines: https://github.com/IMXNOOBX/cs2-external-esp/blob/24731b39cf8aca949ead890560944027a95a36ff/memory-external/hacks/hack.hpp#L7-L15

**Comment by hayk4500** [comment]
Update again))
