### ISSUE TITLE
how to disable team esp

### ISSUE THREAD

**Issue by Mmd645** [IMXNOOBX/cs2-external-esp#10]
great project , how can I disable team esp?

**Comment by Roasterbation** [comment]
@IMXNOOBX Sir Here

**Comment by xXxNozz4rrxXx** [comment]
already did that i will ask for @IMXNOOBX  If hes give me the permission to rework on this 
and upload it to my github with much features etc 

for now to disable the team esp is the basic knowledge of c++ and game hacking 
just go to hack.hpp line 67 and write / edit what i did below 



![image](https://github.com/IMXNOOBX/cs2-external-esp/assets/76511149/0b0cb571-4228-4d5a-8528-98ed6a283431)

**Comment by xXxNozz4rrxXx** [comment]
> great project , how can I disable team esp?
already did that i will ask for @IMXNOOBX If hes give me the permission to rework on this
and upload it to my github with much features etc

for now to disable the team esp is the basic knowledge of c++ and game hacking
just go to hack.hpp line 67 and write / edit what i did below

![image](https://github.com/IMXNOOBX/cs2-external-esp/assets/76511149/93fc3caa-ba2e-4d5f-813d-a6177aadc95c)

@Roasterbation

**Comment by Roasterbation** [comment]
the localteam != playerteam was below with draw renderbox and i tried
editing that last time but didnt work so uh ok.

**Comment by IMXNOOBX** [comment]
Yes that will work without any issues. @xXxNozz4rrxXx I would be more than happy if you wanted to contribute with new features and ideas. if you want to make another project out of it its fine, but i would be more than happy to review them and implement them here if you make a pull request!

**Comment by Roasterbation** [comment]
overlay ESP is the only undetected cheat to be honest.Making external
without any extra precaution will insta ban us after 2 match.Also it
depends if we are closet cheating.Maybe survive a little longer but ban
will be for sure.

**Comment by IMXNOOBX** [comment]
Well that's right, the idea for this project was to keep as simple as possible, to learn what changed in the game. I will still keep it simple as there are many other projects with more features and better written than this on GitHub. but adding a switch for teammate esp or improving the esp with more information wouldn't affect to it's detection and would still keep it simple.

**Comment by Bekston** [comment]
Already implemented in my pull request but much cleaner
