### ISSUE TITLE
Esp still not working after updated offset

### ISSUE THREAD

**Issue by memes231** [IMXNOOBX/cs2-external-esp#100]
huh what please fix it huh ahh

**Comment by ifBars** [comment]
> huh what please fix it huh ahh

**User issue. Works fine for me**
**Offsets**
`{
    "build_number": 13972,
    "dwBuildNumber": 4760852,
    "dwEntityList": 24841456,
    "dwLocalPlayer": 25165832,
    "dwPlantedC4": 25247592,
    "dwViewMatrix": 25228080,
    "m_ArmorValue": 5384,
    "m_bIsDefusing": 5008,
    "m_flC4Blow": 3760,
    "m_flFlashOverlayAlpha": 5212,
    "m_flNextBeep": 3756,
    "m_flTimerLength": 3768,
    "m_hPlayerPawn": 2028,
    "m_iAccount": 64,
    "m_iHealth": 812,
    "m_iTeamNum": 959,
    "m_pClippingWeapon": 4776,
    "m_pGameSceneNode": 784,
    "m_pInGameMoneyServices": 1792,
    "m_sSanitizedPlayerName": 1872,
    "m_szName": 3096,
    "m_vOldOrigin": 4644,
    "m_vecAbsOrigin": 200
}`
