### ISSUE TITLE
[Requests] how to update offsetsby using cs2 dumpers

### ISSUE THREAD

**Issue by memes231** [IMXNOOBX/cs2-external-esp#105]
i hope @IMXNOOBX will answer this

**Comment by ifBars** [comment]
> i hope @IMXNOOBX will answer this

The offsets are automatically updated, you can find them in the offsets.json file.

**Comment by Rusbad7** [comment]
im already update offsets.json file, on 17 november update it's working but 21 update not showing again

**Comment by jhonthedoe** [comment]
There is no "dwLocalPlayer" anymore!

**Comment by ifBars** [comment]
> im already update offsets.json file, on 17 november update it's working but 21 update not showing again

Then your offsets are wrong.

**Comment by ifBars** [comment]
> There is no "dwLocalPlayer" anymore!

Lmfao there 100% is but okay, if you read my replies, you will know that it is dwLocalPlayer in the esp, and dwLocalPlayerController in the dumper.

**Comment by jhonthedoe** [comment]
I did it too the value is 25183512.
But it is STILL NOT WORKING.

You can check mine.

{
    "build_number": 13973,
    "dwBuildNumber": 4764948,
    "dwEntityList": 24859136,
    "dwLocalPlayer": 25183512,
    "dwPlantedC4": 25265272,
    "dwViewMatrix": 25245760,
    "m_ArmorValue": 5384, 
    "m_bIsDefusing": 5032, 
    "m_flC4Blow": 3760, 
    "m_flFlashOverlayAlpha": 5212, 
    "m_flNextBeep": 3756, 
    "m_flTimerLength": 3768, 
    "m_hPlayerPawn": 2028, 
    "m_iAccount": 64, 
    "m_iHealth": 812, 
    "m_iTeamNum": 959, 
    "m_pClippingWeapon": 4776, 
    "m_pGameSceneNode": 784,
    "m_pInGameMoneyServices": 1744,
    "m_sSanitizedPlayerName": 1824,
    "m_szName": 3096, 
    "m_vOldOrigin": 4644, 
    "m_vecAbsOrigin": 200
}

**Comment by memes231** [comment]
> > i hope @IMXNOOBX will answer this
> 
> The offsets are automatically updated by a github bot when CS2 dumper is updated, you can find them in the offsets.json file.
> 
> [offsets.json](https://github.com/IMXNOOBX/cs2-external-esp/blob/main/offsets/offsets.json)

how do i dump dwLocalPlayer

**Comment by memes231** [comment]
no dwlocalplayer why

**Comment by ifBars** [comment]
> dwLocalPlayer in the esp, and dwLocalPlayerController in the dumper.

**dwLocalPlayer in the esp, and dwLocalPlayerController in the dumper...**

**Comment by memes231** [comment]
Ohhhh my baad
