### ISSUE TITLE
Update Laters

### ISSUE THREAD

**Issue by oguz-gun** [IMXNOOBX/cs2-external-esp#107]
ESP does not work. Can you help with the issue?

**Comment by oguz-gun** [comment]
Is there anyone who can help?

**Comment by oguz-gun** [comment]
not working

**Comment by IMXNOOBX** [comment]
Can you please provide more information, or is it just that you havent updated the offsets?

**Comment by oguz-gun** [comment]
![sss](https://github.com/IMXNOOBX/cs2-external-esp/assets/126420458/5c3099f1-d690-43fe-85cd-27380b12e489)

esp not working

**Comment by lekiet1214** [comment]
@oguz-gun 
You can find offsets on [UC reversal thread](https://www.unknowncheats.me/forum/counter-strike-2-a/576077-counter-strike-2-reversal-structs-offsets.html) or  [IMXNOOBX's thread](https://www.unknowncheats.me/forum/counter-strike-2-releases/600259-cs2-external-esp.html).
