### ISSUE TITLE
Great project

### ISSUE THREAD

**Issue by toxic-grl** [IMXNOOBX/cs2-external-esp#11]
It's a great project @IMXNOOBX !
You should put a link to https://www.buymeacoffee.com/ or similar so that people who want to can collaborate

**Comment by IMXNOOBX** [comment]
Hey, thanks for your feedback <3, i do have donations in my profile readme. but i dont think anyone will be donating xd

**Comment by TauCSGO** [comment]
> Hey, thanks for your feedback <3, i do have donations in my profile readme. but i dont think anyone will be donating xd

I just donated and you deserve that other people do too.
I live in a country where the dollar is very expensive, and I could only donate 3 dollars for now, but what matters is the intention.
https://i.gyazo.com/92c95928ed086830fc137ee73f964183.png

**Comment by IMXNOOBX** [comment]
> I just donated and you deserve that other people do too.
> 
> I live in a country where the dollar is very expensive, and I could only donate 3 dollars for now, but what matters is the intention.

Thank you so much!! i will keep the project updated and thanks for your support again! ❤️

**Comment by Mmd645** [comment]
bro answer my issue

**Comment by toxic-grl** [comment]
> > I just donated and you deserve that other people do too.
> > I live in a country where the dollar is very expensive, and I could only donate 3 dollars for now, but what matters is the intention.
> 
> Thank you so much!! i will keep the project updated and thanks for your support again! ❤️

I am "ToXiC GrL" in your discord ♥
