### ISSUE TITLE
Discord version sometimes stop working

### ISSUE THREAD

**Issue by kura6789** [IMXNOOBX/cs2-external-esp#12]
Hello, I'm using discord version of ur project cuz nvidia is lagging for me but I have one problem with it - sometimes stop working for like 30s. It looks like it stops after me or oponent throw nade. I added prints to ur code to see when it stops and looks like somewhere here
```
if (screenpos.z >= 0.01f) {
	printf(" here3?\n\n", head);
	OverlayCord::Drawing::Pixel health_color = { 75,
		(unsigned char)(55 + playerHealth * 2),
		(unsigned char)(255 - playerHealth),
		255
	};
	printf(" here4?\n\n", head);
	OverlayCord::Drawing::DrawRectangle(
		mainFrame,
		screenhead.x - 25.f,
		screenhead.y,
		width,
		height,
		(localTeam == playerTeam ? team_color : enemy_color)
	);
	printf(" here5?\n\n", head);
	OverlayCord::Drawing::DrawRectangle(
		mainFrame,
		screenhead.x - 30.f,
		screenhead.y + (height * (100 - playerHealth) / 100),
		2,
		height - (height * (100 - playerHealth) / 100),
		health_color

	);
	printf(" tu6?\n\n", head);
}
```
Sometimes it stops on "here4?" but if i hash it then it stops after "here5?" Whats wrong here? Can u help?

**Comment by as436twesdzx** [comment]
yes same i cant fix it

**Comment by IMXNOOBX** [comment]
I had the same issue while working with the discord overlay. It doesn't have anything to do with the nades as I've tried several things. It happens randomly every certain time. i couldn't figure out what was causing it. you might want to check the fist messages on the unknowncheats thread. Some users added quite interesting theories about it
