### ISSUE TITLE
Infinite [cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...

### ISSUE THREAD

**Issue by gra439** [IMXNOOBX/cs2-external-esp#134]
[info] Github Repository: https://github.com/IMXNOOBX/cs2-external-esp
[info] Unknowncheats thread: https://www.unknowncheats.me/forum/counter-strike-2-releases/600259-cs2-external-esp.html

[config] Reading configuration.
[updater] Sucessfully read configuration file

[updater] Last GitHub repository update was made by IMXNOOBX on 2024-01-05
[updater] Local file is up to date.

[updater] Reading offsets from file offsets.json.
[updater] Sucessfully read offsets file

[cs2] Waiting for cs2.exe...
[cs2] Attached to cs2.exe

[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...
[cs2] Failed to find module client.dll/engine2.dll, waiting for the game to load it...

My guy needs to figure out the get modules. Also had to modify code slightly (see below)

added #pragma comment(lib, "wininet.lib") after #include <Windows.h> in main.cpp

**Comment by gra439** [comment]
Alr launched game... tried exe before launching game. still didn't work

**Comment by IMXNOOBX** [comment]
Try running as administrator, and you addition shouldnt have anything to do with the inhability of the esp to find the modules

**Comment by gra439** [comment]
That fixed it
