### ISSUE TITLE
It won't work

### ISSUE THREAD

**Issue by aydineray** [IMXNOOBX/cs2-external-esp#139]
It won't work after latest big update of cs2, although as always I updated offsets using cs2-dumper and unknowncheats. could you solve that issue, please?

note : I downloaded latest code and compiled it in vs 2022, it downloaded latest offsets by default but it still won't work

**Comment by aydineray** [comment]
head tracker and skeleton is not working

**Comment by leocdi** [comment]
so you manager to get square and hp/armor arount player @aydineray  ?
