### ISSUE TITLE
Fix please

### ISSUE THREAD

**Issue by Fr0go1** [IMXNOOBX/cs2-external-esp#14]
Allow us to turn off the team overlay. Tell us how to make the overlay fps better (maybe use imgui) and how to make it show on all players, maybe even give it a gui

**Comment by xXxNozz4rrxXx** [comment]
already do that i off the teamp

> Allow us to turn off the team overlay. Tell us how to make the overlay fps better (maybe use imgui) and how to make it show on all players, maybe even give it a gui

already do that , i will add more features to this cheat : 

just for now go to hack.hpp line 67 
and paste this 


if (localTeam != playerTeam)
{
				render::DrawBorderBox(
					g::hdcBuffer,
					screenhead.x - width / 2,
					screenhead.y,
					width,
					height,
					RGB(175, 75, 75)


				);

				render::DrawBorderBox(
					g::hdcBuffer,
					screenhead.x - (width / 2 + 5),
					screenhead.y + (height * (100 - playerHealth) / 100),
					2,
					height - (height * (100 - playerHealth) / 100),
					RGB(
						(255 - playerHealth),
						(55 + playerHealth * 2),
						75
					)
				);

				render::RenderText(
					g::hdcBuffer,
					screenhead.x + (width / 2 + 5),
					screenhead.y,
					playerName.c_str(),
					RGB(75, 75, 175),
					10
				);

				render::RenderText(
					g::hdcBuffer,
					screenhead.x + (width / 2 + 5),
					screenhead.y + 10,
					(std::to_string(playerHealth) + " | HEALTH").c_str(),
					RGB(
						(255 - playerHealth),
						(55 + playerHealth * 2),
						75
					),
					10
				);
};

this will disable the drawing of esp for team
