### ISSUE TITLE
new offsets?

### ISSUE THREAD

**Issue by memorymanager** [IMXNOOBX/cs2-external-esp#145]

**Comment by oguz-gun** [comment]
when update

**Comment by IMXNOOBX** [comment]
https://github.com/IMXNOOBX/cs2-external-esp/issues/107#issuecomment-1833765479

**Comment by memorymanager** [comment]
thanks

**Comment by oguz-gun** [comment]
{
    "yapı_numarası" : 13994 , 
    "dwBuildNumber" : 5322084 , 
    "dwEntityList" : 25903016 , 
    "dwLocalPlayer" : 24286024 , 
    "dwPlantedC4" : 26326280 , 
    "dwViewMatrix" : 26301632 , 
    "m_ArmorValue" : 5488 , 
    "m_bIsDefusing" : 5128 , 
    "m_flC4Blow" : 3848 , 
    "m_flFlashOverlayAlpha" : 5312 , 
    "m_flNextBeep" : 3844 , 
    "m_flTimerLength" : 3856 , 
    "m_hPlayerPawn" : 2020 , 
    "m_iAccount" : 64 , 
    "m_iHealth" : 820 , 
    "m_iTeamNum" : 971 , 
    "m_pClippingWeapon" : 4872 , 
    "m_pGameSceneNode" : 792 , 
    "m_pInGameMoneyServices" : 1784 , 
    "m_sSanitizedPlayerName" : 1864 , 
    "m_szAdı" : 3104 , 
    "m_vOldOrigin" : 4732 , 
    "m_vecAbsOrigin" : 200 , 
    "dwLocalPlayerController" : 26228984 
}

**Comment by oguz-gun** [comment]
{
    "build_number": 13994,
    "dwBuildNumber": 5322084,
    "dwEntityList": 25903016,
    "dwLocalPlayer": 24286024,
    "dwPlantedC4": 26326280,
    "dwViewMatrix": 26301632,
    "m_ArmorValue": 5488,
    "m_bIsDefusing": 5128,
    "m_flC4Blow": 3848,
    "m_flFlashOverlayAlpha": 5312,
    "m_flNextBeep": 3844,
    "m_flTimerLength": 3856,
    "m_hPlayerPawn": 2020,
    "m_iAccount": 64,
    "m_iHealth": 820,
    "m_iTeamNum": 971,
    "m_pClippingWeapon": 4872,
    "m_pGameSceneNode": 792,
    "m_pInGameMoneyServices": 1784,
    "m_sSanitizedPlayerName": 1864,
    "m_szName": 3104,
    "m_vOldOrigin": 4732,
    "m_vecAbsOrigin": 200,
    "dwLocalPlayerController": 26228984
}
