### ISSUE TITLE
esp not working 

### ISSUE THREAD

**Issue by 13374erkash** [IMXNOOBX/cs2-external-esp#15]
hello the esp is not working for me. i updated offsets with dumper and when i start game esp rendering somewhere in map textures with random name but not working on players
![1](https://github.com/IMXNOOBX/cs2-external-esp/assets/146565313/7f0b0e9b-7c5c-4c0a-bd8e-a3599bb75567)

**Comment by VilotStar** [comment]
If you use the offsets provided in the repo currently, they will work, I'm assuming the dumper got the wrong addresses.

**Comment by 13374erkash** [comment]
can you send here good offsets? i tried from github and from dumper no one worked

**Comment by 13374erkash** [comment]
I updated the offsets, now the game does not show ESP at all

**Comment by VilotStar** [comment]
The offsets provided are the correct ones, I have tested and used them myself, compare your offsets to the provided ones

**Comment by 13374erkash** [comment]
yes now its working, maybe you can do tutorial how to update offsets correct? for future updates
