### ISSUE TITLE
Crashes with the skeleton ESP on

### ISSUE THREAD

**Issue by ITS00Vanya** [IMXNOOBX/cs2-external-esp#166]
When the skeleton esp is enabled, it works for 5-10 seconds and then crashes. Is there a way to fix it?

**Comment by IMXNOOBX** [comment]
Its a known issue, sometimes with updates it causes crashes, im unsure why it happens and to be honest i don't have free time to maintain it. I suggest you refer to the unknown cheats thread where the community constantly updates and helps users

**Comment by ITS00Vanya** [comment]
Ok, thanks for answering
