### ISSUE TITLE
Nothing showed after entering the game.

### ISSUE THREAD

**Issue by kuayuetech** [IMXNOOBX/cs2-external-esp#168]
Hi, after I compile the project and run the cs2-external-esp.exe,
it seems like there is no problem at all:
![image](https://github.com/IMXNOOBX/cs2-external-esp/assets/69107987/9cf82470-8a63-4651-85c5-222d6bf64778)
but the it doesn't show anything in the game after I press the hotkeys or change the config file setting to true.
Could you please check what is going wrong?
Thanks.

**Comment by IMXNOOBX** [comment]
I suggest you get the offsets from the unknowncheats thread, those will work fine, the auto updater doesn't get them correctly every time
