### ISSUE TITLE
not working on some players

### ISSUE THREAD

**Issue by 13374erkash** [IMXNOOBX/cs2-external-esp#17]
![image](https://github.com/IMXNOOBX/cs2-external-esp/assets/146565313/bdc4ce9c-538d-466a-8fae-1b976fd8a9d9)

**Comment by bolenacz** [comment]
#define dwLocalPlayer 0x1879C18
#define dwEntityList 0x178c8a8 
#define dwPawnHealth 0x808
#define dwPlayerPawn 0x7fc
#define dwViewMatrix 0x187a700
#define dwSanitizedName 0x720
#define m_iTeamNum 0x3BF
#define m_vecOrigin 0x1214
#define m_iCrosshairId 0x152C
#define m_iShotsFired  0x14d0 
#define m_aimPunchAngle 0x17cc

**Comment by 13374erkash** [comment]
where i put this code?

**Comment by VilotStar** [comment]
There is a config.json file defined externally which you can edit without recompiling, defining the addresses this way isn't needed, also if you pull from the repo currently, it has the newest offsets already.

**Comment by 13374erkash** [comment]
yes i use newest offsets but some players not showing the esp

**Comment by 13374erkash** [comment]
![1](https://github.com/IMXNOOBX/cs2-external-esp/assets/146565313/bc0bd0b2-0e4f-4aa5-b63a-2b50ffef94a6)
same like yesterday

**Comment by IMXNOOBX** [comment]
I will look into it when i get home. I've experienced that issue before but just some unique times that i didn't pay attention to it

**Comment by VilotStar** [comment]
I have also experienced this at times, however I think it may be due to the continuation of checking if the current player is localplayer, as, at times, when I move around quick enough my player still has a esp box around it

**Comment by 13374erkash** [comment]
yes your fix helped thanks
