### ISSUE TITLE
UPDATED OFFSETS

### ISSUE THREAD

**Issue by nutnut2001** [IMXNOOBX/cs2-external-esp#171]
here is the updated offsets u need too copy paste into ya offsets.

known issue that i have found is that the esp is working but only for about 30 seconds and then the cmd closes and the esp glitches across the screen. (not sure how too fix that owner if u could help would be great!)

![image_2024-07-11_031152180](https://github.com/IMXNOOBX/cs2-external-esp/assets/111810391/c179cc9e-86a2-4ae8-baee-c3b0ed226dc1)

[offsets.json](https://github.com/user-attachments/files/16170671/offsets.json)

**Comment by nutnut2001** [comment]
correction too buildnumber -     "build_number": 14020,

**Comment by IMXNOOBX** [comment]
You should make a pull request, if you dont know let me know and i will help you!
