### ISSUE TITLE
improved protection

### ISSUE THREAD

**Issue by bolenacz** [IMXNOOBX/cs2-external-esp#19]
soon this source code will be noticed by vac to prevent this, you must change the way handle_ = OpenProcess(PROCESS_VM_READ, FALSE, pid_)); change the way to NtOpenProcess it opens handle_ from ring0 and this way of handle is unnoticed by vac (memory.cpp 79,107)

**Comment by bolenacz** [comment]
you can use chat-gpt, it will help you in this well :)))

**Comment by VilotStar** [comment]
I'm currently writing a handle hijacker for another cs2 hack, I may pull into this repo with it and that should help decrease detection pretty significantly

**Comment by zuqr** [comment]
i get error from auto_updater.obj lnk2019 when i build
