### ISSUE TITLE
Doesn`t work

### ISSUE THREAD

**Issue by Vladeek** [IMXNOOBX/cs2-external-esp#199]
seems like it doesn`t work. may be problem in offsets, because i hear bips on functional buttons

**Comment by Vladeek** [comment]
seems like it doesn`t work. may be problem in offsets, because i hear bips on functional buttons

**Comment by IMXNOOBX** [comment]
Yes, you will have to update them manually, i suggest you follow the steps in the readme or check the UC thread for more information!
