### ISSUE TITLE
Functions

### ISSUE THREAD

**Issue by Rene0220** [IMXNOOBX/cs2-external-esp#22]
Maybe add new functions to config? Like enabling skeleton esp, rounded box and how much rounded(i tested it but i cant normally code, when u are on bigger distance then rounded is more, idk how to fix it), make more beautiful and maybe add what weapon equiped?

**Comment by Rene0220** [comment]
idk, is real to make glow esp here?

**Comment by VilotStar** [comment]
I imagine at some point there will be settings for this, I haven't really explored chams in cs2 however it is possible in game so it's most likely possible via code

**Comment by Rene0220** [comment]
waiting for updates) im playing 300fps with 0 sleep in render

**Comment by VilotStar** [comment]
It's never a good idea to have 0 sleep, however you can definitely do some calculations to lower the delay per screen, plus it's laggy because it's GDI, using something else would be ideal

**Comment by Rene0220** [comment]
Add auto offset dumper/updater

**Comment by ifBars** [comment]
> Add auto offset dumper/updater

If you compile the source, it can auto update offsets from the repo upon running the program. However if the offsets on the repo are outdated, it won't do a thing really.

**Comment by VilotStar** [comment]
> > Add auto offset dumper/updater
> 
> 
> 
> If you compile the source, it can auto update offsets from the repo upon running the program. However if the offsets on the repo are outdated, it won't do a thing really.

They mean using an address generator, tree are a few on GitHub that auto push updates

**Comment by Qanbaz** [comment]
> idk, i have now very smooth esp with 0 sleep, without any lags and 300 fps

I need to try this, in  which cpp/hpp file did you update this ?

**Comment by ifBars** [comment]
> > idk, i have now very smooth esp with 0 sleep, without any lags and 300 fps
> 
> 
> 
> I need to try this, in  which cpp/hpp file did you update this ?

It is at the bottom of hack.hpp.
