### ISSUE TITLE
Client.dll is missing

### ISSUE THREAD

**Issue by YeetPlayz** [IMXNOOBX/cs2-external-esp#32]
when i saw the video it was shows Client.dll is missing but after the game was opened it shows a success message but mine didnt

**Comment by ifBars** [comment]
> when i saw the video it was shows Client.dll is missing but after the game was opened it shows a success message but mine didnt

The video is from 1 month ago. All you need to do is update your offsets. If you compile the source code on your own, it will auto update the offsets.

**Comment by YeetPlayz** [comment]
> > when i saw the video it was shows Client.dll is missing but after the game was opened it shows a success message but mine didnt
> 
> The video is from 1 month ago. All you need to do is update your offsets. If you compile the source code on your own, it will auto update the offsets.

i did and still doesnt work

**Comment by ifBars** [comment]
> > > when i saw the video it was shows Client.dll is missing but after the game was opened it shows a success message but mine didnt
> > 
> > 
> > The video is from 1 month ago. All you need to do is update your offsets. If you compile the source code on your own, it will auto update the offsets.
> 
> i did and still doesnt work

What offsets are you using?

I have a fork of this that I am using just fine now, if you wanna try that instead

[https://github.com/ifBars/cs2-external-esp/releases/tag/Forkv1](https://github.com/ifBars/cs2-external-esp/releases/tag/Forkv1)

**Comment by YeetPlayz** [comment]
> > > > when i saw the video it was shows Client.dll is missing but after the game was opened it shows a success message but mine didnt
> > > 
> > > 
> > > The video is from 1 month ago. All you need to do is update your offsets. If you compile the source code on your own, it will auto update the offsets.
> > 
> > 
> > i did and still doesnt work
> 
> What offsets are you using?
> 
> I have a fork of this that I am using just fine now, if you wanna try that instead
> 
> https://github.com/ifBars/cs2-external-esp/releases/tag/Forkv1

ill test it ina bit

**Comment by ifBars** [comment]
> > > > > when i saw the video it was shows Client.dll is missing but after the game was opened it shows a success message but mine didnt
> > > > 
> > > > 
> > > > The video is from 1 month ago. All you need to do is update your offsets. If you compile the source code on your own, it will auto update the offsets.
> > > 
> > > 
> > > i did and still doesnt work
> > 
> > 
> > What offsets are you using?
> > I have a fork of this that I am using just fine now, if you wanna try that instead
> > https://github.com/ifBars/cs2-external-esp/releases/tag/Forkv1
> 
> ill test it ina bit

    "dwEntityList": 24684552,
    "dwLocalPlayer": 25656568,
    "dwPawnHealth": 2056,
    "dwPlayerPawn": 2044,
    "m_iPawnArmor": 2060,
    "dwSanitizedName": 1824,
    "dwViewMatrix": 25659360,
    "m_bPawnHasDefuser": 2064,
    "m_iTeamNum": 959,
    "m_vecOrigin": 4628
    
These are the updated offsets

**Comment by YeetPlayz** [comment]
> > > > > > when i saw the video it was shows Client.dll is missing but after the game was opened it shows a success message but mine didnt
> > > > > 
> > > > > 
> > > > > The video is from 1 month ago. All you need to do is update your offsets. If you compile the source code on your own, it will auto update the offsets.
> > > > 
> > > > 
> > > > i did and still doesnt work
> > > 
> > > 
> > > What offsets are you using?
> > > I have a fork of this that I am using just fine now, if you wanna try that instead
> > > https://github.com/ifBars/cs2-external-esp/releases/tag/Forkv1
> > 
> > 
> > ill test it ina bit
> 
> ```
> "dwEntityList": 24684552,
> "dwLocalPlayer": 25656568,
> "dwPawnHealth": 2056,
> "dwPlayerPawn": 2044,
> "m_iPawnArmor": 2060,
> "dwSanitizedName": 1824,
> "dwViewMatrix": 25659360,
> "m_bPawnHasDefuser": 2064,
> "m_iTeamNum": 959,
> "m_vecOrigin": 4628
> ```
> 
> These are the updated offsets

those are the ones im using

**Comment by YeetPlayz** [comment]
> > > > > > when i saw the video it was shows Client.dll is missing but after the game was opened it shows a success message but mine didnt
> > > > > 
> > > > > 
> > > > > The video is from 1 month ago. All you need to do is update your offsets. If you compile the source code on your own, it will auto update the offsets.
> > > > 
> > > > 
> > > > i did and still doesnt work
> > > 
> > > 
> > > What offsets are you using?
> > > I have a fork of this that I am using just fine now, if you wanna try that instead
> > > https://github.com/ifBars/cs2-external-esp/releases/tag/Forkv1
> > 
> > 
> > ill test it ina bit
> 
> ```
> "dwEntityList": 24684552,
> "dwLocalPlayer": 25656568,
> "dwPawnHealth": 2056,
> "dwPlayerPawn": 2044,
> "m_iPawnArmor": 2060,
> "dwSanitizedName": 1824,
> "dwViewMatrix": 25659360,
> "m_bPawnHasDefuser": 2064,
> "m_iTeamNum": 959,
> "m_vecOrigin": 4628
> ```
> 
> These are the updated offsets

plus cs2 just had a update

**Comment by ifBars** [comment]
> > > > > > > when i saw the video it was shows Client.dll is missing but after the game was opened it shows a success message but mine didnt
> > > > > > 
> > > > > > 
> > > > > > The video is from 1 month ago. All you need to do is update your offsets. If you compile the source code on your own, it will auto update the offsets.
> > > > > 
> > > > > 
> > > > > i did and still doesnt work
> > > > 
> > > > 
> > > > What offsets are you using?
> > > > I have a fork of this that I am using just fine now, if you wanna try that instead
> > > > https://github.com/ifBars/cs2-external-esp/releases/tag/Forkv1
> > > 
> > > 
> > > ill test it ina bit
> > 
> > 
> > ```
> > "dwEntityList": 24684552,
> > "dwLocalPlayer": 25656568,
> > "dwPawnHealth": 2056,
> > "dwPlayerPawn": 2044,
> > "m_iPawnArmor": 2060,
> > "dwSanitizedName": 1824,
> > "dwViewMatrix": 25659360,
> > "m_bPawnHasDefuser": 2064,
> > "m_iTeamNum": 959,
> > "m_vecOrigin": 4628
> > ```
> > 
> > 
> > These are the updated offsets
> 
> plus cs2 just had a update

Yes and the offsets were the same as the last update... Which are the ones I just provided to you... I am well aware of this.

**Comment by YeetPlayz** [comment]
> > > > > > > > when i saw the video it was shows Client.dll is missing but after the game was opened it shows a success message but mine didnt
> > > > > > > 
> > > > > > > 
> > > > > > > The video is from 1 month ago. All you need to do is update your offsets. If you compile the source code on your own, it will auto update the offsets.
> > > > > > 
> > > > > > 
> > > > > > i did and still doesnt work
> > > > > 
> > > > > 
> > > > > What offsets are you using?
> > > > > I have a fork of this that I am using just fine now, if you wanna try that instead
> > > > > https://github.com/ifBars/cs2-external-esp/releases/tag/Forkv1
> > > > 
> > > > 
> > > > ill test it ina bit
> > > 
> > > 
> > > ```
> > > "dwEntityList": 24684552,
> > > "dwLocalPlayer": 25656568,
> > > "dwPawnHealth": 2056,
> > > "dwPlayerPawn": 2044,
> > > "m_iPawnArmor": 2060,
> > > "dwSanitizedName": 1824,
> > > "dwViewMatrix": 25659360,
> > > "m_bPawnHasDefuser": 2064,
> > > "m_iTeamNum": 959,
> > > "m_vecOrigin": 4628
> > > ```
> > > 
> > > 
> > > These are the updated offsets
> > 
> > 
> > plus cs2 just had a update
> 
> Yes and the offsets were the same as the last update... Which are the ones I just provided to you... I am well aware of this.

ur ver didnt work btw

**Comment by ifBars** [comment]
> > > > > > > > > when i saw the video it was shows Client.dll is missing but after the game was opened it shows a success message but mine didnt
> > > > > > > > 
> > > > > > > > 
> > > > > > > > The video is from 1 month ago. All you need to do is update your offsets. If you compile the source code on your own, it will auto update the offsets.
> > > > > > > 
> > > > > > > 
> > > > > > > i did and still doesnt work
> > > > > > 
> > > > > > 
> > > > > > What offsets are you using?
> > > > > > I have a fork of this that I am using just fine now, if you wanna try that instead
> > > > > > https://github.com/ifBars/cs2-external-esp/releases/tag/Forkv1
> > > > > 
> > > > > 
> > > > > ill test it ina bit
> > > > 
> > > > 
> > > > ```
> > > > "dwEntityList": 24684552,
> > > > "dwLocalPlayer": 25656568,
> > > > "dwPawnHealth": 2056,
> > > > "dwPlayerPawn": 2044,
> > > > "m_iPawnArmor": 2060,
> > > > "dwSanitizedName": 1824,
> > > > "dwViewMatrix": 25659360,
> > > > "m_bPawnHasDefuser": 2064,
> > > > "m_iTeamNum": 959,
> > > > "m_vecOrigin": 4628
> > > > ```
> > > > 
> > > > 
> > > > These are the updated offsets
> > > 
> > > 
> > > plus cs2 just had a update
> > 
> > 
> > Yes and the offsets were the same as the last update... Which are the ones I just provided to you... I am well aware of this.
> 
> ur ver didnt work btw

You must be doing something wrong on your end, because it works just fine for me.

**Comment by ifBars** [comment]
> > > > > > > > > when i saw the video it was shows Client.dll is missing but after the game was opened it shows a success message but mine didnt
> > > > > > > > 
> > > > > > > > 
> > > > > > > > The video is from 1 month ago. All you need to do is update your offsets. If you compile the source code on your own, it will auto update the offsets.
> > > > > > > 
> > > > > > > 
> > > > > > > i did and still doesnt work
> > > > > > 
> > > > > > 
> > > > > > What offsets are you using?
> > > > > > I have a fork of this that I am using just fine now, if you wanna try that instead
> > > > > > https://github.com/ifBars/cs2-external-esp/releases/tag/Forkv1
> > > > > 
> > > > > 
> > > > > ill test it ina bit
> > > > 
> > > > 
> > > > ```
> > > > "dwEntityList": 24684552,
> > > > "dwLocalPlayer": 25656568,
> > > > "dwPawnHealth": 2056,
> > > > "dwPlayerPawn": 2044,
> > > > "m_iPawnArmor": 2060,
> > > > "dwSanitizedName": 1824,
> > > > "dwViewMatrix": 25659360,
> > > > "m_bPawnHasDefuser": 2064,
> > > > "m_iTeamNum": 959,
> > > > "m_vecOrigin": 4628
> > > > ```
> > > > 
> > > > 
> > > > These are the updated offsets
> > > 
> > > 
> > > plus cs2 just had a update
> > 
> > 
> > Yes and the offsets were the same as the last update... Which are the ones I just provided to you... I am well aware of this.
> 
> ur ver didnt work btw

Is your game in Fullscreen Windowed mode? If not the cheat will not work.

**Comment by YeetPlayz** [comment]
Yea my game is borderless

**Comment by IMXNOOBX** [comment]
You must build the project in x64 configuration. make sure you do that or else it wont be able to work

**Comment by YeetPlayz** [comment]
I did

**Comment by YeetPlayz** [comment]
> You must build the project in x64 configuration. make sure you do that or else it wont be able to work

i did

**Comment by ifBars** [comment]
> > You must build the project in x64 configuration. make sure you do that or else it wont be able to work
> 
> 
> 
> i did

The most recent game update broke it, so it's not going to work currently anyways
