### ISSUE TITLE
New CS2 update - Off

### ISSUE THREAD

**Issue by toxic-grl** [IMXNOOBX/cs2-external-esp#33]
There was a major update to CS2 and although the offsets are updated, it doesn't work.
I think the signatures changed too.

**Comment by ifBars** [comment]
Vouch - Current offsets are outdated

These are the offsets I could find, but I still can't get ESP working. It renders on my own player, but not any other players.

```json
{
    "dwEntityList": 24697944,
    "dwLocalPlayer": 25019624,
	"m_iPawnArmor": 1996,
    "dwPawnHealth": 1992,
    "dwPlayerPawn": 1980,
    "dwSanitizedName": 1824,
    "dwViewMatrix": 25672368,
    "m_iTeamNum": 959,
    "m_vecOrigin": 4628
}

```

**Comment by syafiq99121** [comment]
can u help us master noobx

**Comment by IMXNOOBX** [comment]
Issue resolved by @ifBars

**Comment by syafiq99121** [comment]
esp doesnt work

**Comment by ifBars** [comment]
> esp doesnt work

Are you compiling from source? If you're using the same exe from before, but just updated the offsets, it is not going to work. This is because the entire structure of reading armor and health changed therefore you need to get the updated exe/binary or compile the source code yourself.
