### ISSUE TITLE
New offsets

### ISSUE THREAD

**Issue by vivekchauhan12000** [IMXNOOBX/cs2-external-esp#38]
Please let us know new offsets which are working

**Comment by IMXNOOBX** [comment]
Check out this commit https://github.com/IMXNOOBX/cs2-external-esp/commit/1b1898c541d4c67dc905236dcf533cc2909ffdb4

**Comment by ifBars** [comment]
> Please let us know new offsets which are working

The updated offsets are on the repo, but the way health and armor works has changed, therefor you need to compile the source yourself or download an already compiled binary.
