### ISSUE TITLE
we need the download man..

### ISSUE THREAD

**Issue by internaaaL** [IMXNOOBX/cs2-external-esp#39]
need download link unknowncheats are sleeping brother

**Comment by ifBars** [comment]
> need download link unknowncheats are sleeping brother

Unfortunately unknowncheats does not allow the compiled binary to be uploaded to github, has to be uploaded to their site. If you really cannot wait, compile the source code, it's really not that hard.

**Comment by internaaaL** [comment]
you dont earn money via unknwoncheats btw
they are not ur daddy u can upload the files btw

omfg

**Comment by ifBars** [comment]
> you dont earn money via unknwoncheats btw
> 
> they are not ur daddy u can upload the files btw
> 
> 
> 
> omfg

Well it's against their forum rules, therefore they have every right to either delete your post, giving you no attention, or completely ban you, or both. If you're that impatient check my fork.

**Comment by internaaaL** [comment]
bahaha get fuck bot sucking cuck forum

**Comment by internaaaL** [comment]
sucking too much for only a esp bnahahha ur a fucking dumb man

**Comment by ifBars** [comment]
> sucking too much for only a esp bnahahha ur a fucking dumb man

I'm dumb but yet I was the one to update the cheat to work with the latest game build, so when you do finally figure out how to use it, or someone else compiles it for you, you're welcome.

You're name is internal but yet it seems you have no knowledge of coding at all.

**Comment by internaaaL** [comment]
dude the cheat was good u propose to change some thing and now we are fucked

**Comment by internaaaL** [comment]
u add distance and other useless things man if u want to code good cheat just esp and aimbot is good man u add distance u dont have the esp bomb man ur a big shit i use it cuz i have no time now i will buy good cheat like 20$ per month and it will be better dont think u have the best cheat its the baddest cheat ever hahah

**Comment by something-0001** [comment]
> need download link unknowncheats are sleeping brother
https://gofile.io/d/nDSOzn

You can do a virus scan, I don't really care, it's the compiled binary from Visual Studio.

**Comment by ifBars** [comment]
> u add distance and other useless things man if u want to code good cheat just esp and aimbot is good man u add distance u dont have the esp bomb man ur a big shit i use it cuz i have no time now i will buy good cheat like 20$ per month and it will be better dont think u have the best cheat its the baddest cheat ever hahah

Why don't you just go make it yourself then? It was OP's choice to do it that way.

**Comment by IMXNOOBX** [comment]
This is no place to be toxic, if you want the binary you could compile it yourself instead if you are going to behave like a kid asking for it. And sorry @something-0001 but binary files cannot be linked to this repository, thanks for sharing though!
