### ISSUE TITLE
pls update it

### ISSUE THREAD

**Issue by IMWurden** [IMXNOOBX/cs2-external-esp#42]
update it, yesterday cs2 got updated

**Comment by ifBars** [comment]
> update it, yesterday cs2 got updated

https://github.com/IMXNOOBX/cs2-external-esp/pull/40

It was updated before you even posted this. All you need to do is compile the source code and update the offsets, or just compile source from my repo until the pull request gets merged.

**Comment by ifBars** [comment]
> > > update it, yesterday cs2 got updated
> 
> > 
> 
> > #40
> 
> > 
> 
> > It was updated before you even posted this. All you need to do is compile the source code and update the offsets, or just compile source from my repo until the pull request gets merged.
> 
> 
> 
> where can I get the new offsets?

https://www.unknowncheats.me/forum/counter-strike-2-a/603583-cs2-offset-interface-dumper.html

**Comment by IMWurden** [comment]
> > > > update it, yesterday cs2 got updated
> > 
> > 
> > > 
> > 
> > 
> > > #40
> > 
> > 
> > > 
> > 
> > 
> > > It was updated before you even posted this. All you need to do is compile the source code and update the offsets, or just compile source from my repo until the pull request gets merged.
> > 
> > 
> > where can I get the new offsets?
> 
> https://www.unknowncheats.me/forum/counter-strike-2-a/603583-cs2-offset-interface-dumper.html


i don't find the offset updated, what is the specific link

**Comment by ifBars** [comment]
> > > > > update it, yesterday cs2 got updated
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > #40
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > It was updated before you even posted this. All you need to do is compile the source code and update the offsets, or just compile source from my repo until the pull request gets merged.
> > > 
> > > 
> > > where can I get the new offsets?
> > 
> > 
> > https://www.unknowncheats.me/forum/counter-strike-2-a/603583-cs2-offset-interface-dumper.html
> 
> i don't find the offset updated, what is the specific link

I have given you 2 different places to find the new offsets, I am not going to simply hand them to you here when you can easily find them in **multiple** places, including the offsets folder of this repo...

**Comment by TheBloonsGuy** [comment]
> > > > update it, yesterday cs2 got updated
> > 
> > 
> > > 
> > 
> > 
> > > #40
> > 
> > 
> > > 
> > 
> > 
> > > It was updated before you even posted this. All you need to do is compile the source code and update the offsets, or just compile source from my repo until the pull request gets merged.
> > 
> > 
> > where can I get the new offsets?
> 
> https://www.unknowncheats.me/forum/counter-strike-2-a/603583-cs2-offset-interface-dumper.html

Im bad at programing but i used the tool and i dont know where in the generated files are the offsets can someone help?

**Comment by ifBars** [comment]
> > > > > update it, yesterday cs2 got updated
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > #40
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > It was updated before you even posted this. All you need to do is compile the source code and update the offsets, or just compile source from my repo until the pull request gets merged.
> > > 
> > > 
> > > where can I get the new offsets?
> > 
> > 
> > https://www.unknowncheats.me/forum/counter-strike-2-a/603583-cs2-offset-interface-dumper.html
> 
> Im bad at programing but i used the tool and i dont know where in the generated files are the offsets can someone help?

New offsets have just been [pushed to this repo](https://github.com/IMXNOOBX/cs2-external-esp/blob/main/offsets/offsets.json). For future reference, theres usually only 3-5 offsets that change, copy the name, Ctrl + F -> paste name, and find your new offset. If that is too much for you, wait for new offsets to be pushed here.

**Comment by TheBloonsGuy** [comment]
> > > > > > update it, yesterday cs2 got updated
> > > > 
> > > > 
> > > > > 
> > > > 
> > > > 
> > > > > #40
> > > > 
> > > > 
> > > > > 
> > > > 
> > > > 
> > > > > It was updated before you even posted this. All you need to do is compile the source code and update the offsets, or just compile source from my repo until the pull request gets merged.
> > > > 
> > > > 
> > > > where can I get the new offsets?
> > > 
> > > 
> > > https://www.unknowncheats.me/forum/counter-strike-2-a/603583-cs2-offset-interface-dumper.html
> > 
> > 
> > Im bad at programing but i used the tool and i dont know where in the generated files are the offsets can someone help?
> 
> New offsets have just been [pushed to this repo](https://github.com/IMXNOOBX/cs2-external-esp/blob/main/offsets/offsets.json). For future reference, theres usually only 3-5 offsets that change, copy the name, Ctrl + F -> paste name, and find your new offset. If that is too much for you, wait for new offsets to be pushed here.

ty it worked
