### ISSUE TITLE
Updating Offsets Issue

### ISSUE THREAD

**Issue by ifBars** [IMXNOOBX/cs2-external-esp#45]
****There seems to be an issue pertaining in the way that the cheat handles updating offsets****

*A few people have been having this issue on UC forums. See Images below.*
![image](https://github.com/IMXNOOBX/cs2-external-esp/assets/114284668/230144e0-1fe0-4134-9f6c-ace499916914)
![image](https://github.com/IMXNOOBX/cs2-external-esp/assets/114284668/c7227f1c-fe1f-4d5f-8c40-60dcb983fbb2)
_Below image is caused by the armor value returning a random number, aka wrong offset used_
![image](https://github.com/IMXNOOBX/cs2-external-esp/assets/114284668/d20aea08-c1d3-4064-902b-95d388dbbb84)
_As you can see, they have already updated armor offset, but to no avail_
![image](https://github.com/IMXNOOBX/cs2-external-esp/assets/114284668/f6daa0da-52da-4fcd-8e5c-c1e074a6a346)
_Seems as if updating the offset in auto_updater.hpp fixed the issue possibly_
![image](https://github.com/IMXNOOBX/cs2-external-esp/assets/114284668/9ffb47ea-3575-43bf-9639-8488717a2379)
_Goes to update offsets using offset.json as it is meant to be used_
![image](https://github.com/IMXNOOBX/cs2-external-esp/assets/114284668/467063f9-5e82-4320-a0eb-5a2037eb56ba)
_Once again, they update offsets, but armor still provides wrong value_
![image](https://github.com/IMXNOOBX/cs2-external-esp/assets/114284668/90c01ae1-82f9-433c-8126-7e376dc8dd84)
_Issue fixed by fetching latest repo from my fork at the time, which I believe just updated the auto_updater.hpp offsets to latest game manually, however in theory, this shouldn't had to have been done as offsets.json had latetst offsets_
![image](https://github.com/IMXNOOBX/cs2-external-esp/assets/114284668/46fa2cb3-78cd-4188-8565-d39af7ad5810)

**As far as what exactly is causing this problem:** I am not sure, but I am almost certain it is either the .py for updating offsets or auto_updater cpp or hpp.

**As far as solutions go:** The main thing that seemed to be fixing this, was fetching the latest commit from my fork of the repo at the time, as it's auto_updater.hpp and offsets.json had the latest offsets in it. That is one thing that leads me to believe it is due to the auto updating of offsets. It seems to be something that was changed/added around the 17th or so, as that was when the issue started to arise. The issue has show itself in many different forms, as you have seen in the images. From the correct armor offset in offsets.json not returning the armor value, aka using the old armor offset, to the program saying the build number is outdated & esp not working, even when the offsets.json has the newest build number & offsets.

**Comment by IMXNOOBX** [comment]
It might be due to the version posted in unknowncheats having the auto updater disabled. but i will look into it this weekend

**Comment by ifBars** [comment]
> It might be due to the version posted in unknowncheats having the auto updater disabled. but i will look into it this weekend

I am not sure, as I have talked to people who ran into the issue from both, the version posted in UC, compiling from src of your repo, and compiling from src of my repo. Again I really do not know the exact cause, however it seems someone may have fixed it on UC? I am trying to see if they will share the src.

![image](https://github.com/IMXNOOBX/cs2-external-esp/assets/114284668/7ab785e4-3f01-4dd7-96ff-cc6653e84b3b)

**Comment by ifBars** [comment]
Seems as if the issue has since been resolved/irrelevant
