### ISSUE TITLE
Low fps

### ISSUE THREAD

**Issue by TheBloonsGuy** [IMXNOOBX/cs2-external-esp#50]
I managed to make it work but my fps in now at around 10 anyone knows a fix?

**Comment by ifBars** [comment]
> I managed to make it work but my fps in now at around 10 anyone knows a fix?

This seems to be an issue with C4 esp, you can try pressing F7 to not show distance, weapon, and $. That may help improve performance slightly.

**Comment by VilotStar** [comment]
GDI seems to just run slow in general, moving to a different overlay would be very good for this project

**Comment by ifBars** [comment]
> GDI seems to just run slow in general, moving to a different overlay would be very good for this project

Me and OP hope to soon move over to IMGUI, and implement skeleton. As well as Daived & Tucucu from UC are both working on their own nvidia overlay forks.
