### ISSUE TITLE
I  keep  getting error

### ISSUE THREAD

**Issue by Qanbaz** [IMXNOOBX/cs2-external-esp#51]
![image](https://github.com/IMXNOOBX/cs2-external-esp/assets/67518610/917dfd74-c7e9-4b2e-8d1e-925e52c96d8f)
Not sure whats wrong here. building using VS 2022

**Comment by IMXNOOBX** [comment]
Please check pinned issues, that issue was already reported by in #6

**Comment by Qanbaz** [comment]
Thank you fixed
