### ISSUE TITLE
New game update

### ISSUE THREAD

**Issue by tkqu** [IMXNOOBX/cs2-external-esp#55]
Can you please supply me a new offsets.json update for the new game version as i cant work out how to update it myself.

when i run the script it says the build number is upto date but the esp doesnt show up

**Comment by tkqu** [comment]
{
    "build_number": 13965,
    "dwBuildNumber": 4748564,
    "dwEntityList": 24741688,
    "dwLocalPlayer": 25063768,
    "dwPlantedC4": 25742032,
    "dwViewMatrix": 25716496,
    "m_ArmorValue": 5360,
    "m_bIsDefusing": 5008,
    "m_flC4Blow": 3760,
    "m_flNextBeep": 3756,
    "m_flTimerLength": 3768,
    "m_hPlayerPawn": 1980,
    "m_iAccount": 64,
    "m_iHealth": 812,
    "m_iTeamNum": 959,
    "m_pClippingWeapon": 4752,
    "m_pGameSceneNode": 784,
    "m_pInGameMoneyServices": 1744,
    "m_sSanitizedPlayerName": 1824,
    "m_szName": 3096,
    "m_vecAbsOrigin": 200,
    "m_vecOrigin": 4628
}

this is my current offsets.json

**Comment by ifBars** [comment]
> Can you please supply me a new offsets.json update for the new game version as i cant work out how to update it myself.
> 
> 
> 
> when i run the script it says the build number is upto date but the esp doesnt show up

This is asked probably 3 times every time the game updates. I will update the offsets.json on the repo, when I get a chance to be on my pc. Until then, you can either get your new offsets from the reversal thread on UnknownCheats, or by using a dumper.

**Comment by ifBars** [comment]
[Cs2 Dumper](https://github.com/a2x/cs2-dumper)

**Comment by tkqu** [comment]
alright thankyou for that new to cheats ill know for next time
