### ISSUE TITLE
It closes when i open cs 2

### ISSUE THREAD

**Issue by TheBloonsGuy** [IMXNOOBX/cs2-external-esp#63]
I opened the esp (the newest version) but when i open cs 2 it just dissapears and when i try to open it again it closes after a second

**Comment by ifBars** [comment]
> I opened the esp (the newest version) but when i open cs 2 it just dissapears and when i try to open it again it closes after a second

Are you compiling from source, if so which branch? If you are using the exe uploaded on UC, it does not have the fix for the crash due to weapon names

**Comment by TheBloonsGuy** [comment]
oh thanks i was using the uc one

**Comment by TheBloonsGuy** [comment]
Nvm im too stupid to know how to compile it i only got a zip file from the main branch but idk what to do with it. Sorry for really stupid questions

**Comment by ifBars** [comment]
> Nvm im too stupid to know how to compile it i only got a zip file from the main branch but idk what to do with it. Sorry for really stupid questions

**How to compile using github desktop:** [https://www.youtube.com/watch?v=meoZczd1urE](https://www.youtube.com/watch?v=meoZczd1urE)
