### ISSUE TITLE
Skeleton

### ISSUE THREAD

**Issue by IMWurden** [IMXNOOBX/cs2-external-esp#65]
Add the option in the config to enable the skeleton of the enemies, it will be a very cool feature

**Comment by ifBars** [comment]
> Add the option in the config to enable the skeleton of the enemies, it will be a very cool feature

It does not have skeleton ESP therefore there's no way to add the option to config, as it does not exist. Skeleton may be added in the future but no promises.

**Comment by Qanbaz** [comment]
@ifBars, would we be able to  implement skeleton even with an external cheat?, I am  very  new to this and I think logically it should be possible hence we are not injecting anything, correct me and pardon my lack of knowledge.

**Comment by ifBars** [comment]
> @ifBars, would we be able to  implement skeleton even with an external cheat?, I am  very  new to this and I think logically it should not be possible hence we are not injecting anything, correct me and pardon my lack of knowledge.

The experimental branch already reads bone array and draws a circle on player heads. So yes you can implement skeleton, as all you need to do is read process memory and then draw at the read locations.
