### ISSUE TITLE
Offsets

### ISSUE THREAD

**Issue by IMWurden** [IMXNOOBX/cs2-external-esp#66]
Can someone give me an updated offset? i updated them manually but they don't work

**Comment by ifBars** [comment]
{
    "build_number": 13966,
    "dwLocalPlayer": 25140232,
    "dwEntityList": 24815848,
    "dwViewMatrix": 25792624,
    "dwBuildNumber": 4752660,
    "dwPlantedC4": 25811704,
    "m_flC4Blow": 3760,
    "m_flNextBeep": 3756,
    "m_flTimerLength": 3768,
    "m_pInGameMoneyServices": 1744,
    "m_iAccount": 64,
    "m_vecAbsOrigin": 200,
    "m_pGameSceneNode": 784,
    "m_flFlashOverlayAlpha": 5204,
    "m_bIsDefusing": 5024,
    "m_szName": 3096,
    "m_pClippingWeapon": 4768,
    "m_ArmorValue": 5376,
    "m_iHealth": 812,
    "m_hPlayerPawn": 1980,
    "m_sSanitizedPlayerName": 1824,
    "m_iTeamNum": 959,
    "m_vecOrigin": 4644
}
