### ISSUE TITLE
Shield Bug

### ISSUE THREAD

**Issue by IMWurden** [IMXNOOBX/cs2-external-esp#69]
The shield with the new offsets is broken because it goes upwards of kilometers

**Comment by ifBars** [comment]
It was working just fine for me a few hours ago. I did have the issue on death match.

**Comment by IMWurden** [comment]
me in competitive, how can i fix?

**Comment by IMWurden** [comment]
the blue shield bar goes up infinitely, how did u fixed?

**Comment by ifBars** [comment]
> the blue shield bar goes up infinitely, how did u fixed?

This issue was caused by a pull request that added a space after the armor value offset, effectively making it not update. The experimental branch has been updated to fix this issue, and will be merged to main soon.
