### ISSUE TITLE
update_offsets.py error

### ISSUE THREAD

**Issue by IMWurden** [IMXNOOBX/cs2-external-esp#71]
Every time i open the file update_offsets,py in the offsets folder i get this error

Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\dll injector\cs2-external-esp-main\offsets\update_offsets.py", line 36, in <module>
    dest_data["dwBuildNumber"] = source_data["engine_2dll"]["data"]["dwBuildNumber"]["value"]
KeyError: 'engine_2dll'

**Comment by IMWurden** [comment]
how can i fix?

**Comment by ifBars** [comment]
> how can i fix?

**Fixed:** [https://github.com/IMXNOOBX/cs2-external-esp/commit/8c87d10f8dd282c9dd1160d0acb31c8c5f4820b6](https://github.com/IMXNOOBX/cs2-external-esp/commit/8c87d10f8dd282c9dd1160d0acb31c8c5f4820b6)
