### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by TheBloonsGuy** [IMXNOOBX/cs2-external-esp#72]
I have compiled the newest version and it launches properly, but when i play a match there are no esp boxes. Anyone knows a fix?

**Comment by ifBars** [comment]
> I have compiled the newest version and it launches properly, but when i play a match there are no esp boxes. Anyone knows a fix?

You are most likely using the wrong offsets or compiling it wrong.

**Comment by TheBloonsGuy** [comment]
Idk i have the offsets updated and i followed the tutorial

**Comment by ifBars** [comment]
> Idk i have the offsets updated and i followed the tutorial

I will try it later, but it was working perfectly for me yesterday. The latest offsets are on the last page of the thread on UC.

**Comment by oguz-gun** [comment]
not working

**Comment by ifBars** [comment]
> not working
> Idk i have the offsets updated and i followed the tutorial

It works just fine for me as of 11/4/23 2:34 PM MST. User error.

**Latest Offsets:** [https://www.unknowncheats.me/forum/3905305-post649.html](https://www.unknowncheats.me/forum/3905305-post649.html)
