### ISSUE TITLE
Armor values

### ISSUE THREAD

**Issue by LytexWZ** [IMXNOOBX/cs2-external-esp#76]
Armor value seems to be attached to another value and it is showing another output, 
![image](https://github.com/IMXNOOBX/cs2-external-esp/assets/72569213/b3359eb4-6a07-40a7-9cda-5b5e7d60100f)

**Comment by ifBars** [comment]
Already fixed. [https://github.com/IMXNOOBX/cs2-external-esp/issues/69](https://github.com/IMXNOOBX/cs2-external-esp/issues/69)
