### ISSUE TITLE
Exception thrown at 0x00007FF8B38D350A (ntdll.dll) in cs2-external-esp.exe: 0xC0000008: An invalid handle was specified.

### ISSUE THREAD

**Issue by memes231** [IMXNOOBX/cs2-external-esp#86]
How to fix this

**Comment by IMXNOOBX** [comment]
Thats caused when attaching to the proccess. try disabling any AV or openning as administrator.

**Comment by memes231** [comment]
Ok thanks for solving i using run without debugger
