### ISSUE TITLE
Skeleton ESP cause crash

### ISSUE THREAD

**Issue by lekiet1214** [IMXNOOBX/cs2-external-esp#87]
When I turn on Skeleton (F8), the ESP work for a few seconds (competitive) before crashing. In practice mode, the esp work for about 1-2 minutes then crash.

```Exception thrown at 0x00007FF70DD39D15 in cs2-external-esp.exe: 0xC0000005: Access violation reading location 0x0000000000000008.```

**Comment by IMWurden** [comment]
same issue, pls fix it

**Comment by IMXNOOBX** [comment]
> When I turn on Skeleton (F8), the ESP work for a few seconds (competitive) before crashing. In practice mode, the esp work for about 1-2 minutes then crash.
> 
> 
> 
> ```Exception thrown at 0x00007FF70DD39D15 in cs2-external-esp.exe: 0xC0000005: Access violation reading location 0x0000000000000008.```

I haven't had time to test it, thanks for reporting it. you might want to use an older commit instead

**Comment by ifBars** [comment]
> When I turn on Skeleton (F8), the ESP work for a few seconds (competitive) before crashing. In practice mode, the esp work for about 1-2 minutes then crash.
> 
> 
> 
> ```Exception thrown at 0x00007FF70DD39D15 in cs2-external-esp.exe: 0xC0000005: Access violation reading location 0x0000000000000008.```

I have not experienced this issue at all. I also don't play competitive though. Reading the entire skeleton at once might improve performance.

**Comment by ifBars** [comment]
> When I turn on Skeleton (F8), the ESP work for a few seconds (competitive) before crashing. In practice mode, the esp work for about 1-2 minutes then crash.
> 
> `Exception thrown at 0x00007FF70DD39D15 in cs2-external-esp.exe: 0xC0000005: Access violation reading location 0x0000000000000008.`

Further looking into the issue, it is most likely caused to bone array just returning horrible values sometimes, however I could be wrong.

**Comment by IMWurden** [comment]
when a fix?

**Comment by ifBars** [comment]
Null checks for game scene node & bone array have been added, should fix the issue
