### ISSUE TITLE
Head

### ISSUE THREAD

**Issue by IMWurden** [IMXNOOBX/cs2-external-esp#88]
Add the option to enable/disable Head circle

**Comment by ifBars** [comment]
> Add the option to enable/disable Head circle

Already been added to a part of skeleton using F8

**Comment by IMWurden** [comment]
it will be more cool if there is the possible to just enable the head circle

**Comment by IMXNOOBX** [comment]
Sounds nice

**Comment by ifBars** [comment]
> it will be more cool if there is the possible to just enable the head circle

Will add this soon 👍

**Comment by ifBars** [comment]
> it will be more cool if there is the possible to just enable the head circle

Added in PR #90
