### ISSUE TITLE
help！

### ISSUE THREAD

**Issue by Leg-rings** [IMXNOOBX/cs2-external-esp#9]
for (int i = 1; i < 32; i++) {
     (8 * (i & 0x7FFF) >> 9)
}
The result of this function is always 0，I don't know how it works, both on C++ and in Python，Sorry, I'm a newbie, please help me

**Comment by Leg-rings** [comment]
(8 * (i & 0x7FFF) >> 9) Its result is always zero

**Comment by IMXNOOBX** [comment]
Thats because the address in memory has changed, you have to fix your address in config.hpp
