### ISSUE TITLE
Non of the ESP features are working.

### ISSUE THREAD

**Issue by jhonthedoe** [IMXNOOBX/cs2-external-esp#94]
Please fix it.

**Comment by ifBars** [comment]
> Please fix it.

update your offsets and maybe it will work kek

**Comment by jhonthedoe** [comment]
I already tried to update it but it is not working.
Please help

**Comment by ifBars** [comment]
> I already tried to update it but it is not working. Please help

`
{
    "build_number": 13969,
    "dwBuildNumber": 4764964,
    "dwEntityList": 24828656,
    "dwLocalPlayer": 25152968,
    "dwPlantedC4": 25234648,
    "dwViewMatrix": 25215232,
    "m_ArmorValue": 5384,
    "m_bIsDefusing": 5008,
    "m_flC4Blow": 3760,
    "m_flFlashOverlayAlpha": 5212,
    "m_flNextBeep": 3756,
    "m_flTimerLength": 3768,
    "m_hPlayerPawn": 2004,
    "m_iAccount": 64,
    "m_iHealth": 812,
    "m_iTeamNum": 959,
    "m_pClippingWeapon": 4776,
    "m_pGameSceneNode": 784,
    "m_pInGameMoneyServices": 1744,
    "m_sSanitizedPlayerName": 1848,
    "m_szName": 3096,
    "m_vOldOrigin": 4644,
    "m_vecAbsOrigin": 200
}
`
