### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by IMWurden** [IMXNOOBX/cs2-external-esp#95]
Sometimes the exe crashs

**Comment by IMWurden** [comment]
And the name don't show up, the enemies are named "M"

**Comment by IMXNOOBX** [comment]
> Sometimes the exe crashs

You can avoid the crashes by disabling skeleton esp. we will work on improving it as now its causing crashes while reading from memory

**Comment by IMXNOOBX** [comment]
> And the name don't show up, the enemies are named "M"

Investigating it, most likely there is a changed offset but im looking it

**Comment by ifBars** [comment]
> Sometimes the exe crashs

Compile from experimental build and it should fix it

**Comment by ifBars** [comment]
> > And the name don't show up, the enemies are named "M"
> 
> Investigating it, most likely there is a changed offset but im looking it 

I was trying to fix this not too long ago. The offsets are fine, with my ImGui I am reading names the exact same way and exact same offset but for some reason it's not working on yours.

**Comment by IMWurden** [comment]
it crashes also if u have the head circle enabled

**Comment by ifBars** [comment]
> it crashes also if u have the head circle enabled

Same issue with skeleton, head circle also uses bone array, it's just the bone array returning weird values.

**Comment by IMWurden** [comment]
when a fix
