### ISSUE TITLE
ESP Feature Still Not Working

### ISSUE THREAD

**Issue by jhonthedoe** [IMXNOOBX/cs2-external-esp#96]
The featured offsets are not working.
There are just distance shower in the upper left edge on the screen.
Please help me.

The offsets I have;

{
    "build_number": 13969,
    "dwBuildNumber": 4764964,
    "dwEntityList": 24828656,
    "dwLocalPlayer": 25152968,
    "dwPlantedC4": 25234648,
    "dwViewMatrix": 25215232,
    "m_ArmorValue": 5384,
    "m_bIsDefusing": 5008,
    "m_flC4Blow": 3760,
    "m_flFlashOverlayAlpha": 5212,
    "m_flNextBeep": 3756,
    "m_flTimerLength": 3768,
    "m_hPlayerPawn": 2004,
    "m_iAccount": 64,
    "m_iHealth": 812,
    "m_iTeamNum": 959,
    "m_pClippingWeapon": 4776,
    "m_pGameSceneNode": 784,
    "m_pInGameMoneyServices": 1744,
    "m_sSanitizedPlayerName": 1848,
    "m_szName": 3096,
    "m_vOldOrigin": 4644,
    "m_vecAbsOrigin": 200
}

**Comment by IMXNOOBX** [comment]
Could you provide an screenshot please. i cant undrestand what you mean

**Comment by jhonthedoe** [comment]
When I first open the program, ESP does not work. Then it turns off on its own. When I turn it on again during the match, it opens, but then it closes itself again within 3-4 seconds.

**Comment by jhonthedoe** [comment]
I really like the old version of this source.
I am really appericiate your work.
Can you just provide this offsets to update the previous version?

{
    "build_number": 13962,
    "dwBuildNumber": 4748564,
    "dwEntityList": 24706184,
    "dwLocalPlayer": 25027848,
    "dwPlayerPawn": 1980,
    "dwSanitizedName": 1824,
    "dwViewMatrix": 25680560,
    "m_iHealth": 812,
    "m_iTeamNum": 959,
    "m_vecOrigin": 4628
}

**Comment by IMXNOOBX** [comment]
> When I first open the program, ESP does not work. Then it turns off on its own. When I turn it on again during the match, it opens, but then it closes itself again within 3-4 seconds.

disable bone/skeleton esp. we are working to improve it and fix the crashes related to it. you can use the latest offsets from the repository if yours don't work.

**Comment by jhonthedoe** [comment]
I already did it but latest offsets you uploaded do not include those ones.
I just need those ones to update previous ones.

"dwPlayerPawn": 1980,
"dwSanitizedName": 1824,

**Comment by ifBars** [comment]
> The featured offsets are not working.
> 
> There are just distance shower in the upper left edge on the screen.
> 
> Please help me.
> 
> 
> 
> The offsets I have;
> 
> 
> 
> {
> 
>     "build_number": 13969,
> 
>     "dwBuildNumber": 4764964,
> 
>     "dwEntityList": 24828656,
> 
>     "dwLocalPlayer": 25152968,
> 
>     "dwPlantedC4": 25234648,
> 
>     "dwViewMatrix": 25215232,
> 
>     "m_ArmorValue": 5384,
> 
>     "m_bIsDefusing": 5008,
> 
>     "m_flC4Blow": 3760,
> 
>     "m_flFlashOverlayAlpha": 5212,
> 
>     "m_flNextBeep": 3756,
> 
>     "m_flTimerLength": 3768,
> 
>     "m_hPlayerPawn": 2004,
> 
>     "m_iAccount": 64,
> 
>     "m_iHealth": 812,
> 
>     "m_iTeamNum": 959,
> 
>     "m_pClippingWeapon": 4776,
> 
>     "m_pGameSceneNode": 784,
> 
>     "m_pInGameMoneyServices": 1744,
> 
>     "m_sSanitizedPlayerName": 1848,
> 
>     "m_szName": 3096,
> 
>     "m_vOldOrigin": 4644,
> 
>     "m_vecAbsOrigin": 200
> 
> }

You need to open the cheat after you are in game already

**Comment by ifBars** [comment]
> I really like the old version of this source.
> 
> I am really appericiate your work.
> 
> Can you just provide this offsets to update the previous version?
> 
> 
> 
> {
> 
>     "build_number": 13962,
> 
>     "dwBuildNumber": 4748564,
> 
>     "dwEntityList": 24706184,
> 
>     "dwLocalPlayer": 25027848,
> 
>     "dwPlayerPawn": 1980,
> 
>     "dwSanitizedName": 1824,
> 
>     "dwViewMatrix": 25680560,
> 
>     "m_iHealth": 812,
> 
>     "m_iTeamNum": 959,
> 
>     "m_vecOrigin": 4628
> 
> }
> 
> 

The same offsets you posted on the beginning, are the offsets that are going to work for every version of this cheat. Disable skeleton esp, compile from experimental build as it has checks for null bones. Don't open the cheat until your in game. If you do all of this and it's still not working, then it's gotta be something to do with your PC, because it works like a charm for me.

**Comment by ifBars** [comment]
> I already did it but latest offsets you uploaded do not include those ones.
> 
> I just need those ones to update previous ones.
> 
> 
> 
> "dwPlayerPawn": 1980,
> 
> "dwSanitizedName": 1824,

[new offsets](https://github.com/IMXNOOBX/cs2-external-esp/pull/97)
