### ISSUE TITLE
ESP Feature Still Not Working !!!

### ISSUE THREAD

**Issue by Kaira3535** [IMXNOOBX/cs2-external-esp#98]
dude we can't update the offsets because some offset names don't appear in a2x's dumper, that is, they can't be found, there are only a few in offset.json

**Comment by IMXNOOBX** [comment]
> dude we can't update the offsets because some offset names don't appear in a2x's dumper, that is, they can't be found, there are only a few in offset.json

I think the problem is on your end. All the offsets are updated in that same repository. And you can find the latest offsets in `/offsets/offsets.json` in this same repository

**Comment by ifBars** [comment]
> dude we can't update the offsets because some offset names don't appear in a2x's dumper, that is, they can't be found, there are only a few in offset.json

User issue. dwLocalPlayer is dwLocalPlayerController in a2x's dumper. The rest that you are looking for are in client.dll.json not offsets.json. kek
