### ISSUE TITLE
Just Working After Second Injection

### ISSUE THREAD

**Issue by jhonthedoe** [IMXNOOBX/cs2-external-esp#99]
I did everything you said and deleted Skeleton ESP, updated offsets and it's working actually.
But it is not working on first injection.
I have to inject on match to use it.
Are there any possible way to fix it?

Thank you a lot. 🙏

**Comment by ifBars** [comment]
> I did everything you said and deleted Skeleton ESP, updated offsets and it's working actually. But it is not working on first injection. I have to inject on match to use it. Are there any possible way to fix it?
> 
> Thank you a lot. 🙏

As I have mentioned before, if you load the ESP before the game there is a chance it will not work. Open the exe after you already have your game open. Oh and by the way, this cheat doesn't "inject" anything at all.

**Comment by jhonthedoe** [comment]
I know it is not injecting anything i truned .exe fil to .dll file and injected in notepad.exe but anyways thanks for help.

**Comment by ifBars** [comment]
> I know it is not injecting anything i truned .exe file to .dll file and injected in notepad.exe but anyways thanks for help.

![image](https://github.com/IMXNOOBX/cs2-external-esp/assets/114284668/c6eafc7c-ecd7-4a35-b8c9-447dae8e291a)
